# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='megapixels',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
