# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200716_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countRating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
