# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
    ]
