# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200713_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
